### ISSUE TITLE
KX-Portal backend server crashing with TypeError: Cannot read properties of null (reading 'message')

### ISSUE THREAD

**Issue by patdel76** [Accenture/kx.as.code#336]
The backend server is crashing.
`TypeError: Cannot read properties of null (reading 'message')`

```
[1] /usr/share/kx.as.code/workspace/kx-portal/client/backend/server.js:100
[1]         console.log(error.message);
[1]                           ^
[1] 
[1] TypeError: Cannot read properties of null (reading 'message')
[1]     at Request._callback (/usr/share/kx.as.code/workspace/kx-portal/client/backend/server.js:100:27)
[1]     at Request.self.callback (/usr/share/kx.as.code/workspace/kx-portal/client/node_modules/request/request.js:185:22)
[1]     at Request.emit (node:events:513:28)
[1]     at Request.<anonymous> (/usr/share/kx.as.code/workspace/kx-portal/client/node_modules/request/request.js:1154:10)
[1]     at Request.emit (node:events:513:28)
[1]     at IncomingMessage.<anonymous> (/usr/share/kx.as.code/workspace/kx-portal/client/node_modules/request/request.js:1076:12)
[1]     at Object.onceWrapper (node:events:627:28)
[1]     at IncomingMessage.emit (node:events:525:35)
[1]     at endReadableNT (node:internal/streams/readable:1358:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[1] {"level":"error","message":"Forever detected script exited with code: 1"}
[1] {"level":"error","message":"Script restart attempt #1"}
[1] listening on 5001
[1] checkRmqConn triggered.
[1] /usr/share/kx.as.code/workspace/kx-portal/client/backend/server.js:100
[1]         console.log(error.message);
[1]                           ^
[1] 
[1] TypeError: Cannot read properties of null (reading 'message')
[1]     at Request._callback (/usr/share/kx.as.code/workspace/kx-portal/client/backend/server.js:100:27)
[1]     at Request.self.callback (/usr/share/kx.as.code/workspace/kx-portal/client/node_modules/request/request.js:185:22)
[1]     at Request.emit (node:events:513:28)
[1]     at Request.<anonymous> (/usr/share/kx.as.code/workspace/kx-portal/client/node_modules/request/request.js:1154:10)
[1]     at Request.emit (node:events:513:28)
[1]     at IncomingMessage.<anonymous> (/usr/share/kx.as.code/workspace/kx-portal/client/node_modules/request/request.js:1076:12
```

**Comment by patdel76** [comment]
After a re-install it worked, so not sure what was causing the error...

**Comment by patdel76** [comment]
Closing this for now, as I have not been able to repeat this error.
